#!/usr/bin/python3

import random
import string

def password_maker():
   Uppercase = string.ascii_uppercase
   Lowercase = string.ascii_lowercase
   digits    = string.digits
   symbols   = "!@#%$*"

   password = Uppercase + Lowercase + digits + symbols

   password_length = random.randint(10,15)
   
   random.shuffle(password)
   print(password)
